### ISSUE TITLE
Excellent work

### ISSUE THREAD

**Issue by amerkoleci** [mellinoe/ShaderGen#1]
Hi,

Recently I started also adding shader generation logic using C#, similar as you, how would you handle the generation logic? as MSBuild task? I suppose that the generation should be not deployed with existing C# project, also reference to Microsoft.CodeAnalysis.CSharp is not usuable prefered on final target? 

Just asking how you plan to handle this.
Thanks,

Amer

**Comment by mellinoe** [comment]
Hey Amer,

I'm still plugging away at this, so I haven't really figured out everything yet. Previously, I was using this project to hook into the build, but it had some limitations and wasn't exactly designed for what I'm doing here. https://github.com/AArnott/CodeGeneration.Roslyn

I will probably end up doing something very similar, though. There is an MSBuild task in a nuget package which invokes a "Dotnet Tool" taking a bunch of parameters. The tool then searches through the compilation context (which is constructed from MSBuild properties) and generates extra code based on that.

And yeah, I will need to separate out the stuff which goes into your product code (like the attributes), from the stuff that actually does the code generation.

**Comment by amerkoleci** [comment]
I see,
I tried to add quickly the MSBuild task and integrate it into project but had some trouble, will wait until you add the generation logic :)

**Comment by mellinoe** [comment]
Hey @amerkoleci -- I added the ShaderGen.Build project, which has some basic MSBuild integration in it.

I'm using it in Veldrid now to generate some shaders for a new demo program. https://github.com/mellinoe/veldrid/blob/master/demo/Main/Shaders/Skybox.cs

Do you have your shader generation project anywhere that I could look at? After building this out for a bit, I have something that works decent enough, but is really messy. I want to go back and rewrite a lot of it now that I know how Roslyn works 😄

**Comment by amerkoleci** [comment]
Hey @mellinoe, I had some local code on my PC.

I've added swizzle support for Vectors and started adding some Half, Bool and Int vector, once I'm able I will try to create pull request :)

**Comment by mellinoe** [comment]
Cool -- swizzle support will be nice for this. I'm just making really long constructor calls at the moment...

**Comment by amerkoleci** [comment]
Just created the pull request, see #2

**Comment by ghuntley** [comment]
Check out https://github.com/paulcbetts/refit/tree/master/InterfaceStubGenerator.BuildTasks for msbuild task insights
