### ISSUE TITLE
ShaderGen doesn't escape paths when passing to HLSL Compiler

### ISSUE THREAD

**Issue by thargy** [mellinoe/ShaderGen#60]
When a shader path has a space in it then HLSL compilation fails:
>Failed to compile HLSL: StdOut: , StdErr: Too many files specified ('Control\Veldrid-Samples\bin\obj\TexturedCube\Cube-vertex.hlsl' was the last one), use /? to get usage information.

_(Full path was "D:\Source Control\\..." so is splitting on space_

The issue is due to line 308 of `ShaderGen.App.Program`'s `CompileHlsl` method which sets the args:
`                string args = $"/T {profile} /E {entryPoint} {shaderPath} /Fo {outputPath}";`

Quoting the parameters fixes, so I will submit a pull-request.

**Comment by feliwir** [comment]
I can confirm this error. We got it aswell
