### ISSUE TITLE
Instancing

### ISSUE THREAD

**Issue by erictuvesson** [mellinoe/ShaderGen#8]
Hi, is there a way to do instancing?

**Comment by mellinoe** [comment]
Could you clarify what you mean? Instancing is controlled by how you issue your draw commands, not really how you write your shaders. You can read from ShaderBuiltins.InstanceID to get the instance's ID (`SV_instanceID`, `gl_InstanceID`, etc.).

**Comment by erictuvesson** [comment]
Sorry for not being more specific, I can't generate a Matrix4x4 array. 

I get "Shader resource fields must be simple blittable structures." when I use Matrix4x4[]. And using ArraySizeAttribute doesn't make any difference.

**Comment by erictuvesson** [comment]
While reading though the test code I noticed that I can do it like this, I guess it solves the problem.

```
public InstanceInfo Instances;

public struct InstanceInfo
{
    [ArraySize(4)] 
    public InstanceData[] Instances;
}

public struct InstanceData
{
    public Matrix4x4 World;
}
```
