### ISSUE TITLE
[Suggestion] Add JetBrains.Annotations

### ISSUE THREAD

**Issue by thargy** [mellinoe/ShaderGen#82]
Hi,

JetBrains Resharper is very popular, and something I've used extensively over the years.  It's particularly good at providing warnings for code issues like potential null reference exceptions, and works with the [Rider IDE](https://www.jetbrains.com/rider/).

To enhance static analysis you can mark a library with attributes such as `[NotNull]`, `[CanBeNull]` and the incredibly powerful `[ContractAnnotation]` all of which allow R# to spot potential code issues.

These attributes are available via the [JetBrains.Annotations NuGet](https://www.nuget.org/packages/JetBrains.Annotations/) and are effectively transparent to anyone not using R#.  Source is available [on GitHub](https://github.com/JetBrains/ExternalAnnotations) and uses the MIT license.

Is it something that we could add in?

**Comment by mellinoe** [comment]
I don't have a problem with adding a build-only dependency for this repository, but I don't want to force downstream users to reference any extra packages. It looks like that is possible based on the description:

> All usages of ReSharper Annotations attributes are erased from metadata by default, which means no actual binary reference to 'JetBrains.Annotations.dll' assembly is produced

So I think it's fine to use it here. I wish there were something free and based on Roslyn that was available, but nothing like that is available, AFAIK. The nullability stuff will probably be obviated by C# 8 features, which I'm planning to use everywhere once it's available.

**Comment by msmshazan** [comment]
I am on the opinion of reduce cluttering of the code base with R# or other third party tooling code

**Comment by thargy** [comment]
Happy to close this as R# is becoming less popular/necessary anyway.
